import datetime

swimmers = [
 {'class': '7',
  'club_id': 'CCRR',
  'dob': datetime.datetime(1988, 1, 1, 0, 0),
  'email': '',
  'first': 'Arrianne',
  'group': 'G',
  'id': 85,
  'last': 'Weisner',
  'mailTo': 'Patrick & Wendi Weisner',
  'sex': 'F',
  'swimmer_id': '010188ARRNWEIS'},
 {'class': '9',
  'club_id': 'CCRR',
  'dob': datetime.datetime(1986, 1, 2, 0, 0),
  'email': 'orbs@home.net',
  'first': 'Robert',
  'group': 'G',
  'id': 75,
  'last': 'Orbison',
  'mailTo': 'Andrew & Susan Orbison',
  'sex': 'M',
  'swimmer_id': '010286ROBAORBI'},
 {'class': '6',
  'club_id': 'CCRR',
  'dob': datetime.datetime(1989, 1, 10, 0, 0),
  'email': 'brighteyes@home.com',
  'first': 'Kelly',
  'group': 'G',
  'id': 311,
  'last': 'Walton',
  'mailTo': 'Dana & Trey Walton',
  'sex': 'F',
  'swimmer_id': '011089KELBWALT'},
 {'class': '9',
  'club_id': 'CCRR',
  'dob': datetime.datetime(1986, 1, 15, 0, 0),
  'email': '3js@hotmail.com',
  'first': 'Julie',
  'group': 'G',
  'id': 23,
  'last': 'Kerr',
  'mailTo': 'Joni & Jonathan Kerr',
  'sex': 'F',
  'swimmer_id': '011586JULAKERR'}
]


data = {'club': {'id': 'CCRR', 'name': 'Carwell County River Racers'},
        'date': '02/15/2015',
        'heats': [{'distance': '50',
                   'dives': '1',
                   'gender': 'G',
                   'id': '1',
                   'individual/relay': 'I',
                   'maxage': '10',
                   'minage': '0',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '50',
                   'dives': '1',
                   'gender': 'B',
                   'id': '2',
                   'individual/relay': 'I',
                   'maxage': '10',
                   'minage': '0',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '3',
                   'individual/relay': 'I',
                   'maxage': '12',
                   'minage': '0',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '3',
                   'individual/relay': 'I',
                   'maxage': '14',
                   'minage': '13',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '3',
                   'individual/relay': 'I',
                   'maxage': '16',
                   'minage': '15',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '3',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '17',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '4',
                   'individual/relay': 'I',
                   'maxage': '12',
                   'minage': '0',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '4',
                   'individual/relay': 'I',
                   'maxage': '14',
                   'minage': '13',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '4',
                   'individual/relay': 'I',
                   'maxage': '16',
                   'minage': '15',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '4',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '17',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '200',
                   'dives': '1',
                   'gender': 'G',
                   'id': '5',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '0',
                   'style': 'E',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '200',
                   'dives': '1',
                   'gender': 'B',
                   'id': '6',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '0',
                   'style': 'E',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '50',
                   'dives': '1',
                   'gender': 'G',
                   'id': '7',
                   'individual/relay': 'I',
                   'maxage': '10',
                   'minage': '0',
                   'style': 'D',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '50',
                   'dives': '1',
                   'gender': 'B',
                   'id': '8',
                   'individual/relay': 'I',
                   'maxage': '10',
                   'minage': '0',
                   'style': 'D',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '9',
                   'individual/relay': 'I',
                   'maxage': '12',
                   'minage': '0',
                   'style': 'D',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '9',
                   'individual/relay': 'I',
                   'maxage': '14',
                   'minage': '13',
                   'style': 'D',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '9',
                   'individual/relay': 'I',
                   'maxage': '16',
                   'minage': '15',
                   'style': 'D',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '9',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '17',
                   'style': 'D',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '10',
                   'individual/relay': 'I',
                   'maxage': '12',
                   'minage': '0',
                   'style': 'D',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '10',
                   'individual/relay': 'I',
                   'maxage': '14',
                   'minage': '13',
                   'style': 'D',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '10',
                   'individual/relay': 'I',
                   'maxage': '16',
                   'minage': '15',
                   'style': 'D',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '10',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '17',
                   'style': 'D',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '50',
                   'dives': '1',
                   'gender': 'G',
                   'id': '11',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '0',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '50',
                   'dives': '1',
                   'gender': 'B',
                   'id': '12',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '0',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '200',
                   'dives': '1',
                   'gender': 'G',
                   'id': '13',
                   'individual/relay': 'R',
                   'maxage': '14',
                   'minage': '0',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '200',
                   'dives': '1',
                   'gender': 'B',
                   'id': '14',
                   'individual/relay': 'R',
                   'maxage': '14',
                   'minage': '0',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '200',
                   'dives': '1',
                   'gender': 'G',
                   'id': '15',
                   'individual/relay': 'R',
                   'maxage': '109',
                   'minage': '15',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '200',
                   'dives': '1',
                   'gender': 'B',
                   'id': '16',
                   'individual/relay': 'R',
                   'maxage': '109',
                   'minage': '15',
                   'style': 'A',
                   'time': '08:45AM',
                   'type': 'F'},
                  {'distance': '200',
                   'dives': '1',
                   'gender': 'G',
                   'id': '17',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '0',
                   'style': 'A',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '200',
                   'dives': '1',
                   'gender': 'B',
                   'id': '18',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '0',
                   'style': 'A',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '50',
                   'dives': '1',
                   'gender': 'G',
                   'id': '19',
                   'individual/relay': 'I',
                   'maxage': '10',
                   'minage': '0',
                   'style': 'C',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '50',
                   'dives': '1',
                   'gender': 'B',
                   'id': '20',
                   'individual/relay': 'I',
                   'maxage': '10',
                   'minage': '0',
                   'style': 'C',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '21',
                   'individual/relay': 'I',
                   'maxage': '12',
                   'minage': '0',
                   'style': 'C',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '21',
                   'individual/relay': 'I',
                   'maxage': '14',
                   'minage': '13',
                   'style': 'C',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '21',
                   'individual/relay': 'I',
                   'maxage': '16',
                   'minage': '15',
                   'style': 'C',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '21',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '17',
                   'style': 'C',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '22',
                   'individual/relay': 'I',
                   'maxage': '12',
                   'minage': '0',
                   'style': 'C',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '22',
                   'individual/relay': 'I',
                   'maxage': '14',
                   'minage': '13',
                   'style': 'C',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '22',
                   'individual/relay': 'I',
                   'maxage': '16',
                   'minage': '15',
                   'style': 'C',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '22',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '17',
                   'style': 'C',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '50',
                   'dives': '1',
                   'gender': 'G',
                   'id': '25',
                   'individual/relay': 'I',
                   'maxage': '10',
                   'minage': '0',
                   'style': 'B',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '50',
                   'dives': '1',
                   'gender': 'B',
                   'id': '26',
                   'individual/relay': 'I',
                   'maxage': '10',
                   'minage': '0',
                   'style': 'B',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '27',
                   'individual/relay': 'I',
                   'maxage': '12',
                   'minage': '0',
                   'style': 'B',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '27',
                   'individual/relay': 'I',
                   'maxage': '14',
                   'minage': '13',
                   'style': 'B',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '27',
                   'individual/relay': 'I',
                   'maxage': '16',
                   'minage': '15',
                   'style': 'B',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'G',
                   'id': '27',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '17',
                   'style': 'B',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '28',
                   'individual/relay': 'I',
                   'maxage': '12',
                   'minage': '0',
                   'style': 'B',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '28',
                   'individual/relay': 'I',
                   'maxage': '14',
                   'minage': '13',
                   'style': 'B',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '28',
                   'individual/relay': 'I',
                   'maxage': '16',
                   'minage': '15',
                   'style': 'B',
                   'time': '03:30PM',
                   'type': 'F'},
                  {'distance': '100',
                   'dives': '1',
                   'gender': 'B',
                   'id': '28',
                   'individual/relay': 'I',
                   'maxage': '109',
                   'minage': '17',
                   'style': 'B',
                   'time': '03:30PM',
                   'type': 'F'}],
        'location': 'National Aquatic Centre, Abbotstown, Dublin',
        'swimmers': {'010188ARRNWEIS': {'class': '7',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1988, 1, 1, 0, 0),
                                        'email': 'amazinmom@spacenet.com',
                                        'first': 'Arrianne',
                                        'group': 'G',
                                        'id': 85,
                                        'last': 'Weisner',
                                        'mailTo': 'Patrick & Wendi Weisner',
                                        'sex': 'F',
                                        'swimmer_id': '010188ARRNWEIS'},
                     '010286ROBAORBI': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 1, 2, 0, 0),
                                        'email': 'orbs@home.net',
                                        'first': 'Robert',
                                        'group': 'G',
                                        'id': 75,
                                        'last': 'Orbison',
                                        'mailTo': 'Andrew & Susan Orbison',
                                        'sex': 'M',
                                        'swimmer_id': '010286ROBAORBI'},
                     '011089KELBWALT': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 1, 10, 0, 0),
                                        'email': 'brighteyes@home.com',
                                        'first': 'Kelly',
                                        'group': 'G',
                                        'id': 311,
                                        'last': 'Walton',
                                        'mailTo': 'Dana & Trey Walton',
                                        'sex': 'F',
                                        'swimmer_id': '011089KELBWALT'},
                     '011586JULAKERR': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 1, 15, 0, 0),
                                        'email': '3js@hotmail.com',
                                        'first': 'Julie',
                                        'group': 'G',
                                        'id': 23,
                                        'last': 'Kerr',
                                        'mailTo': 'Joni & Jonathan Kerr',
                                        'sex': 'F',
                                        'swimmer_id': '011586JULAKERR'},
                     '012184DANLFESP': {'class': '12',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1984, 1, 21, 0, 0),
                                        'email': 'ang_sam@hotmail.com',
                                        'first': 'Daniel',
                                        'group': 'G',
                                        'id': 119,
                                        'last': 'Fesperman',
                                        'mailTo': 'Angela & Sam Fesperman',
                                        'sex': 'M',
                                        'swimmer_id': '012184DANLFESP'},
                     '012289SHALSTAN': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 1, 22, 0, 0),
                                        'email': '',
                                        'first': 'Shannah',
                                        'group': 'G',
                                        'id': 273,
                                        'last': 'Stanton',
                                        'mailTo': '',
                                        'sex': 'F',
                                        'swimmer_id': '012289SHALSTAN'},
                     '012487LYNAHAUS': {'class': '8',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1987, 1, 24, 0, 0),
                                        'email': 'hausermans@hotmail.com',
                                        'first': 'Lynne',
                                        'group': 'G',
                                        'id': 322,
                                        'last': 'Hauserman',
                                        'mailTo': 'Greg & Kay Hauserman',
                                        'sex': 'F',
                                        'swimmer_id': '012487LYNAHAUS'},
                     '012989RYASWHAL': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 1, 29, 0, 0),
                                        'email': 'mysite@hotmail.com',
                                        'first': 'Ryan',
                                        'group': 'G',
                                        'id': 88,
                                        'last': 'Whaley',
                                        'mailTo': 'Wanda Whaley',
                                        'sex': 'M',
                                        'swimmer_id': '012989RYASWHAL'},
                     '013087LEATSKIN': {'class': '8',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1987, 1, 30, 0, 0),
                                        'email': 'fishfam@aol.com',
                                        'first': 'Leanne',
                                        'group': 'G',
                                        'id': 42,
                                        'last': 'Skinner',
                                        'mailTo': 'Lavonne & Zander Skinner',
                                        'sex': 'F',
                                        'swimmer_id': '013087LEATSKIN'},
                     '020189TABBSNYD': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 2, 1, 0, 0),
                                        'email': 'goswim@wizconnect.net',
                                        'first': 'Tabitha',
                                        'group': 'G',
                                        'id': 271,
                                        'last': 'Snyder',
                                        'mailTo': 'Douglas & Delia Snyder',
                                        'sex': 'F',
                                        'swimmer_id': '020189TABBSNYD'},
                     '020286TRIKRENN': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 2, 2, 0, 0),
                                        'email': 'birdwatcher@aol.com',
                                        'first': 'Trina',
                                        'group': 'G',
                                        'id': 209,
                                        'last': 'Renn',
                                        'mailTo': 'Denise & Greg Renn',
                                        'sex': 'F',
                                        'swimmer_id': '020286TRIKRENN'},
                     '020390SARJDAWS': {'class': '4',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1990, 2, 3, 0, 0),
                                        'email': 'happyfam@hotmail.com',
                                        'first': 'Sara',
                                        'group': 'G',
                                        'id': 196,
                                        'last': 'Dawson',
                                        'mailTo': 'Richard and Amy Dawson',
                                        'sex': 'F',
                                        'swimmer_id': '020390SARJDAWS'},
                     '020686DEVSSIMP': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 2, 6, 0, 0),
                                        'email': 'tam_29@hostpro.com',
                                        'first': 'Devon',
                                        'group': 'G',
                                        'id': 328,
                                        'last': 'Simpson',
                                        'mailTo': 'Tamara & Jack Simpson',
                                        'sex': 'F',
                                        'swimmer_id': '020686DEVSSIMP'},
                     '020986JUSNSANT': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 2, 9, 0, 0),
                                        'email': 'justus@home.com',
                                        'first': 'Justine',
                                        'group': 'G',
                                        'id': 327,
                                        'last': 'Santos',
                                        'mailTo': 'Nick & Mariah Santos',
                                        'sex': 'F',
                                        'swimmer_id': '020986JUSNSANT'},
                     '021591SHETRESP': {'class': '4',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1991, 2, 15, 0, 0),
                                        'email': 'alwaysswimn@quicknet.com',
                                        'first': 'Sherry',
                                        'group': 'G',
                                        'id': 97,
                                        'last': 'Respess',
                                        'mailTo': 'Katherine & Calvin Respess',
                                        'sex': 'F',
                                        'swimmer_id': '021591SHETRESP'},
                     '021691JEDMKRUG': {'class': '4',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1991, 2, 16, 0, 0),
                                        'email': 'krugers@netmail.com',
                                        'first': 'Jedia',
                                        'group': 'G',
                                        'id': 172,
                                        'last': 'Kruger',
                                        'mailTo': 'Marc & Linda Kruger',
                                        'sex': 'M',
                                        'swimmer_id': '021691JEDMKRUG'},
                     '022189KARLMORE': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 2, 21, 0, 0),
                                        'email': 'gmorenus@stny.rr.com',
                                        'first': 'KARA',
                                        'group': 'G',
                                        'id': 320,
                                        'last': 'MORENUS',
                                        'mailTo': 'Amy & Gary Morenus',
                                        'sex': 'F',
                                        'swimmer_id': '022189KARLMORE'},
                     '022790SIGMPENN': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1990, 2, 27, 0, 0),
                                        'email': 'pennj33@comconnect.net',
                                        'first': 'Sigourney',
                                        'group': 'G',
                                        'id': 307,
                                        'last': 'Penn',
                                        'mailTo': 'Artie & Jane Penn',
                                        'sex': 'F',
                                        'swimmer_id': '022790SIGMPENN'},
                     '030484LYNJNEAL': {'class': '12',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1984, 3, 4, 0, 0),
                                        'email': 'nealfam@yahoo.com',
                                        'first': 'Lynn',
                                        'group': 'G',
                                        'id': 33,
                                        'last': 'Neal',
                                        'mailTo': 'Harrison & Victoria Neal',
                                        'sex': 'F',
                                        'swimmer_id': '030484LYNJNEAL'},
                     '031089JANLHEND': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 3, 10, 0, 0),
                                        'email': '',
                                        'first': 'Janet',
                                        'group': 'G',
                                        'id': 308,
                                        'last': 'Henderson',
                                        'mailTo': 'Sam & Gloria Henderson',
                                        'sex': 'F',
                                        'swimmer_id': '031089JANLHEND'},
                     '031388LESKGAIT': {'class': '8',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1988, 3, 13, 0, 0),
                                        'email': '',
                                        'first': 'Leslie',
                                        'group': 'G',
                                        'id': 321,
                                        'last': 'Gaither',
                                        'mailTo': 'Larry & Necia Gaither',
                                        'sex': 'F',
                                        'swimmer_id': '031388LESKGAIT'},
                     '031586RHOLLAMM': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 3, 15, 0, 0),
                                        'email': 'lammfam@networks.com',
                                        'first': 'Rhonda',
                                        'group': 'G',
                                        'id': 67,
                                        'last': 'Lamm',
                                        'mailTo': 'Dave & Jan Lamm',
                                        'sex': 'F',
                                        'swimmer_id': '031586RHOLLAMM'},
                     '032190CARECLAY': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1990, 3, 21, 0, 0),
                                        'email': 'playclay@hotmail.com',
                                        'first': 'Caroline',
                                        'group': 'G',
                                        'id': 236,
                                        'last': 'Clay',
                                        'mailTo': 'Daniel and Regina Clay',
                                        'sex': 'F',
                                        'swimmer_id': '032190CARECLAY'},
                     '032593ASHMRESP': {'class': '2',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1993, 3, 25, 0, 0),
                                        'email': '',
                                        'first': 'Ashlynn',
                                        'group': 'B',
                                        'id': 259,
                                        'last': 'Respess',
                                        'mailTo': '',
                                        'sex': 'F',
                                        'swimmer_id': '032593ASHMRESP'},
                     '032691MATRKRUG': {'class': '4',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1991, 3, 26, 0, 0),
                                        'email': '',
                                        'first': 'Matthew',
                                        'group': 'G',
                                        'id': 64,
                                        'last': 'Kruger',
                                        'mailTo': 'Lisa & Mark Krol',
                                        'sex': 'M',
                                        'swimmer_id': '032691MATRKRUG'},
                     '032889TUCDBRAD': {'class': '10',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 3, 28, 0, 0),
                                        'email': 'Bradley12@hotmail.com',
                                        'first': 'Tucker',
                                        'group': 'G',
                                        'id': 233,
                                        'last': 'Bradley',
                                        'mailTo': 'Bill and Sara Bradley',
                                        'sex': 'F',
                                        'swimmer_id': '032889TUCDBRAD'},
                     '040884DANJHAWT': {'class': '11',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1984, 4, 8, 0, 0),
                                        'email': 'ptcruisers@worldnet.com',
                                        'first': 'Daniel',
                                        'group': 'G',
                                        'id': 152,
                                        'last': 'Hawthorne',
                                        'mailTo': 'Pam & Todd Hawthorne',
                                        'sex': 'M',
                                        'swimmer_id': '040884DANJHAWT'},
                     '041090MARLMONT': {'class': '5',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1990, 4, 10, 0, 0),
                                        'email': 'allofus@home.com',
                                        'first': 'Marilyn',
                                        'group': 'G',
                                        'id': 185,
                                        'last': 'Montrose',
                                        'mailTo': 'Bernie & Melinda Montrose',
                                        'sex': 'F',
                                        'swimmer_id': '041090MARLMONT'},
                     '041193GWEESTAN': {'class': '2',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1993, 4, 11, 0, 0),
                                        'email': 'stantons4@aol.com',
                                        'first': 'Gwendolyn',
                                        'group': 'B',
                                        'id': 291,
                                        'last': 'Stanton',
                                        'mailTo': 'Lance & Vicki Stanton',
                                        'sex': 'F',
                                        'swimmer_id': '041193GWEESTAN'},
                     '042188MARNMUNS': {'class': '7',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1988, 4, 21, 0, 0),
                                        'email': 'MUNSON.V-M@JUNO.COM',
                                        'first': 'MARIANNE',
                                        'group': 'G',
                                        'id': 6,
                                        'last': 'MUNSON',
                                        'mailTo': 'Margaret & Victor Munson',
                                        'sex': 'F',
                                        'swimmer_id': '042188MARNMUNS'},
                     '042493SHAJEDGE': {'class': '2',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1993, 4, 24, 0, 0),
                                        'email': 'edge@coastalnet.com',
                                        'first': 'Shanna',
                                        'group': 'B',
                                        'id': 310,
                                        'last': 'Edgerton',
                                        'mailTo': 'Sandra & Tommy Edgerton',
                                        'sex': 'F',
                                        'swimmer_id': '042493SHAJEDGE'},
                     '050684ABIJMURP': {'class': '11',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1984, 5, 6, 0, 0),
                                        'email': 'skmurphy56@cs.com',
                                        'first': 'ABIGAIL',
                                        'group': 'G',
                                        'id': 252,
                                        'last': 'MURPHY',
                                        'mailTo': 'Sue & Kevin Murphy',
                                        'sex': 'F',
                                        'swimmer_id': '050684ABIJMURP'},
                     '051891MICRSELI': {'class': '4',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1991, 5, 18, 0, 0),
                                        'email': 'funhouse@home.com',
                                        'first': 'Michelle',
                                        'group': 'G',
                                        'id': 309,
                                        'last': 'Selinski',
                                        'mailTo': 'Janet & Noel Selinski',
                                        'sex': 'M',
                                        'swimmer_id': '051891MICRSELI'},
                     '052186SAMCALLE': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 5, 21, 0, 0),
                                        'email': 'rjsallen@aol.com',
                                        'first': 'Samantha',
                                        'group': 'G',
                                        'id': 55,
                                        'last': 'Allen',
                                        'mailTo': 'Raymond and Jan Allen',
                                        'sex': 'F',
                                        'swimmer_id': '052186SAMCALLE'},
                     '060488ABISFRIT': {'class': '7',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1988, 6, 4, 0, 0),
                                        'email': 'Lfritz@hypernet.com',
                                        'first': 'Abigal',
                                        'group': 'G',
                                        'id': 16,
                                        'last': 'Fritz',
                                        'mailTo': 'Lewis & Gwyn Fritz',
                                        'sex': 'F',
                                        'swimmer_id': '060488ABISFRIT'},
                     '060786MANAMASO': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 6, 7, 0, 0),
                                        'email': 'jmcintos@stny.rr.com',
                                        'first': 'Mandy',
                                        'group': 'G',
                                        'id': 31,
                                        'last': 'Mason',
                                        'mailTo': 'Justin & Angela Mason',
                                        'sex': 'F',
                                        'swimmer_id': '060786MANAMASO'},
                     '061085JANRFRAZ': {'class': '11',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1985, 6, 10, 0, 0),
                                        'email': '',
                                        'first': 'Janet',
                                        'group': 'G',
                                        'id': 286,
                                        'last': 'Frazier',
                                        'mailTo': 'Sandy & Lorne Frazier',
                                        'sex': 'F',
                                        'swimmer_id': '061085JANRFRAZ'},
                     '061091SHALEDGE': {'class': '4',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1991, 6, 10, 0, 0),
                                        'email': '',
                                        'first': 'Sharon',
                                        'group': 'G',
                                        'id': 89,
                                        'last': 'Edgerton',
                                        'mailTo': 'Sandra & Tommy Edgerton',
                                        'sex': 'F',
                                        'swimmer_id': '061091SHALEDGE'},
                     '061185DIABMCCR': {'class': '10',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1985, 6, 11, 0, 0),
                                        'email': '',
                                        'first': 'Diana',
                                        'group': 'G',
                                        'id': 121,
                                        'last': 'McCray',
                                        'mailTo': 'Tracy & Don McCray',
                                        'sex': 'F',
                                        'swimmer_id': '061185DIABMCCR'},
                     '061685SAMLSAND': {'class': '11',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1985, 10, 16, 0, 0),
                                        'email': '',
                                        'first': 'Samuel',
                                        'group': 'G',
                                        'id': 264,
                                        'last': 'Sanders',
                                        'mailTo': 'Sheila & James Sanders',
                                        'sex': 'M',
                                        'swimmer_id': '061685SAMLSAND'},
                     '062790STEGLAND': {'class': '5',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1990, 6, 27, 0, 0),
                                        'email': 'treyland@nyc.net',
                                        'first': 'Stevie',
                                        'group': 'G',
                                        'id': 162,
                                        'last': 'Landau',
                                        'mailTo': 'Trey & Ellen Landau',
                                        'sex': 'M',
                                        'swimmer_id': '062790STEGLAND'},
                     '070189ARLKDANV': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 7, 1, 0, 0),
                                        'email': 'danville3@aol.com',
                                        'first': 'Arlene',
                                        'group': 'G',
                                        'id': 176,
                                        'last': 'Danville',
                                        'mailTo': 'Lynn & Mack Danville',
                                        'sex': 'F',
                                        'swimmer_id': '070189ARLKDANV'},
                     '070290JAMGCOST': {'class': '5',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1990, 7, 2, 0, 0),
                                        'email': 'costner3@webnet.com',
                                        'first': 'Jamie',
                                        'group': 'B',
                                        'id': 313,
                                        'last': 'Costner',
                                        'mailTo': 'Dan and Maggie Costner',
                                        'sex': 'M',
                                        'swimmer_id': '070290JAMGCOST'},
                     '070389CATGBOCE': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 7, 3, 0, 0),
                                        'email': 'bocelli401@aol.com',
                                        'first': 'Cathy',
                                        'group': 'G',
                                        'id': 232,
                                        'last': 'Bocelli',
                                        'mailTo': 'Jack and Shellyi Bocelli',
                                        'sex': 'F',
                                        'swimmer_id': '070389CATGBOCE'},
                     '071591KATRTUCK': {'class': '4',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1991, 7, 15, 0, 0),
                                        'email': 'TuckerRS@corning.com',
                                        'first': 'Gina',
                                        'group': 'G',
                                        'id': 241,
                                        'last': 'Tolson',
                                        'mailTo': 'Michelle & Roy Tucker',
                                        'sex': 'F',
                                        'swimmer_id': '071591KATRTUCK'},
                     '071786ERIJSTIL': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 7, 17, 0, 0),
                                        'email': 'cricket@home.com',
                                        'first': 'Erin',
                                        'group': 'G',
                                        'id': 40,
                                        'last': 'Stilley',
                                        'mailTo': 'Jim & Cassandra Stilley',
                                        'sex': 'F',
                                        'swimmer_id': '071786ERIJSTIL'},
                     '072183KATLBROW': {'class': '12',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1983, 7, 21, 0, 0),
                                        'email': 'bettyboop@earthlink.com',
                                        'first': 'Katie',
                                        'group': 'G',
                                        'id': 279,
                                        'last': 'Brown',
                                        'mailTo': 'Edward and Elizabeth Brown',
                                        'sex': 'F',
                                        'swimmer_id': '072183KATLBROW'},
                     '073084TABLLINS': {'class': '11',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1984, 7, 30, 0, 0),
                                        'email': 'janlin@yahoo.com',
                                        'first': 'Tabitha',
                                        'group': 'G',
                                        'id': 65,
                                        'last': 'Linson',
                                        'mailTo': 'Randy & Janice Linson',
                                        'sex': 'F',
                                        'swimmer_id': '073084TABLLINS'},
                     '073185MARCASOR': {'class': '10',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1985, 7, 31, 0, 0),
                                        'email': 'JAV12@windnet.com',
                                        'first': 'Mary',
                                        'group': 'G',
                                        'id': 230,
                                        'last': 'Asorphi',
                                        'mailTo': 'John and Bobbi Asorphi',
                                        'sex': 'F',
                                        'swimmer_id': '073185MARCASOR'},
                     '080188FRAEHAME': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1988, 8, 1, 0, 0),
                                        'email': '',
                                        'first': 'Fran',
                                        'group': 'G',
                                        'id': 178,
                                        'last': 'Hames',
                                        'mailTo': 'Mark & Jessie Hames',
                                        'sex': 'F',
                                        'swimmer_id': '080188FRAEHAME'},
                     '080386DONLWIND': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 8, 3, 0, 0),
                                        'email': 'qwindham@homeplace.com',
                                        'first': 'Donna',
                                        'group': 'G',
                                        'id': 193,
                                        'last': 'Windham',
                                        'mailTo': 'Quincy & Yasmine Windham',
                                        'sex': 'F',
                                        'swimmer_id': '080386DONLWIND'},
                     '081186SANLHALE': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 8, 11, 0, 0),
                                        'email': 'haleyes@camnet.com',
                                        'first': 'Sandra',
                                        'group': 'G',
                                        'id': 102,
                                        'last': 'Hale',
                                        'mailTo': 'Bobby & Rebecca Hale',
                                        'sex': 'F',
                                        'swimmer_id': '081186SANLHALE'},
                     '081187MARCTULL': {'class': '8',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1987, 8, 11, 0, 0),
                                        'email': 'rogerrabbit@yahoo.com',
                                        'first': 'Marissa',
                                        'group': 'G',
                                        'id': 242,
                                        'last': 'Tull',
                                        'mailTo': 'Eileen & Roger Tull',
                                        'sex': 'F',
                                        'swimmer_id': '081187MARCTULL'},
                     '081584TINATRUL': {'class': '11',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1984, 8, 15, 0, 0),
                                        'email': 'luckyone@cconnect.net',
                                        'first': 'Tina',
                                        'group': 'G',
                                        'id': 225,
                                        'last': 'Truluck',
                                        'mailTo': 'Thomas & Renee Truluck',
                                        'sex': 'F',
                                        'swimmer_id': '081584TINATRUL'},
                     '081691SHAGPAYT': {'class': '4',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1991, 8, 16, 0, 0),
                                        'email': '',
                                        'first': 'Shanna',
                                        'group': 'B',
                                        'id': 316,
                                        'last': 'Payton',
                                        'mailTo': '',
                                        'sex': 'F',
                                        'swimmer_id': '081691SHAGPAYT'},
                     '081989RENSTANN': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 8, 19, 0, 0),
                                        'email': 'swimntanrs@proconnect.com',
                                        'first': 'Rena',
                                        'group': 'G',
                                        'id': 240,
                                        'last': 'Tanner',
                                        'mailTo': 'Sandra & Harry Tanner',
                                        'sex': 'F',
                                        'swimmer_id': '081989RENSTANN'},
                     '082292HENPPAYT': {'class': '3',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1992, 8, 22, 0, 0),
                                        'email': '',
                                        'first': 'Henny',
                                        'group': 'B',
                                        'id': 317,
                                        'last': 'Payton',
                                        'mailTo': 'Kendra & Rashad Payton',
                                        'sex': 'M',
                                        'swimmer_id': '082292HENPPAYT'},
                     '082983CHAJZAYT': {'class': '11',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1983, 8, 29, 0, 0),
                                        'email': 'z28@cconnect.net',
                                        'first': 'Chance',
                                        'group': 'G',
                                        'id': 46,
                                        'last': 'Zaytoun',
                                        'mailTo': 'Wesley & Angela Zaytoun',
                                        'sex': 'M',
                                        'swimmer_id': '082983CHAJZAYT'},
                     '090886ANNKTRIP': {'class': '10',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 9, 8, 0, 0),
                                        'email': 'trippup@homenet.com',
                                        'first': 'Anna',
                                        'group': 'G',
                                        'id': 278,
                                        'last': 'Tripplet',
                                        'mailTo': 'Michael & Briana Tripplet',
                                        'sex': 'F',
                                        'swimmer_id': '090886ANNKTRIP'},
                     '091088BETGGUIO': {'class': '7',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1988, 9, 10, 0, 0),
                                        'email': 'becca@hotmail.com',
                                        'first': 'Bethany',
                                        'group': 'G',
                                        'id': 293,
                                        'last': 'Guion',
                                        'mailTo': 'Rebecca & Larry Guion',
                                        'sex': 'F',
                                        'swimmer_id': '091088BETGGUIO'},
                     '091788HEADCONN': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1988, 9, 17, 0, 0),
                                        'email': 'mannyc@aol.com',
                                        'first': 'Heather',
                                        'group': 'G',
                                        'id': 330,
                                        'last': 'Conner',
                                        'mailTo': 'Manuel and Jeannie Conner',
                                        'sex': 'F',
                                        'swimmer_id': '091788HEADCONN'},
                     '092089MADEPONT': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 9, 20, 0, 0),
                                        'email': 'supermom@hotmail.com',
                                        'first': 'Madison',
                                        'group': 'G',
                                        'id': 314,
                                        'last': 'Pontiff',
                                        'mailTo': 'Joey & Zelda Pontiff',
                                        'sex': 'F',
                                        'swimmer_id': '092089MADEPONT'},
                     '093089KELCFOLS': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 9, 30, 0, 0),
                                        'email': 'chancesare@worldnet.com',
                                        'first': 'Kelsey',
                                        'group': 'G',
                                        'id': 59,
                                        'last': 'Folsom',
                                        'mailTo': 'Kendra & Chance Folsom',
                                        'sex': 'F',
                                        'swimmer_id': '093089KELCFOLS'},
                     '100186GAIKJAMI': {'class': '8',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 10, 1, 0, 0),
                                        'email': 'djandshirl@worldnet.com',
                                        'first': 'Gail',
                                        'group': 'G',
                                        'id': 274,
                                        'last': 'Jamison',
                                        'mailTo': 'Dan & Shirley Jamison',
                                        'sex': 'F',
                                        'swimmer_id': '100186GAIKJAMI'},
                     '100285LORLBAYS': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1985, 10, 2, 0, 0),
                                        'email': 'jbays13@hyperlink.com',
                                        'first': 'Lori',
                                        'group': 'G',
                                        'id': 296,
                                        'last': 'Bays',
                                        'mailTo': 'Jeff and Leslie Bays',
                                        'sex': 'F',
                                        'swimmer_id': '100285LORLBAYS'},
                     '100386JARLYOUN': {'class': '8',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 10, 3, 0, 0),
                                        'email': 'younce_3@hotmail.com',
                                        'first': 'Jarrett',
                                        'group': 'G',
                                        'id': 45,
                                        'last': 'Younce',
                                        'mailTo': 'Sam & Diane Younce',
                                        'sex': 'M',
                                        'swimmer_id': '100386JARLYOUN'},
                     '100690GRAJFIEL': {'class': '5',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1990, 10, 6, 0, 0),
                                        'email': 'Fieldfam@hotmail.com',
                                        'first': 'Grace',
                                        'group': 'G',
                                        'id': 58,
                                        'last': 'Fields',
                                        'mailTo': 'Claire & Davis Fields',
                                        'sex': 'F',
                                        'swimmer_id': '100690GRAJFIEL'},
                     '101089DANWBRAN': {'class': '5',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 10, 10, 0, 0),
                                        'email': 'TBranton12@aol.com',
                                        'first': 'Daniel',
                                        'group': 'G',
                                        'id': 234,
                                        'last': 'Branton',
                                        'mailTo': 'Tom and Kathy Branton',
                                        'sex': 'M',
                                        'swimmer_id': '101089DANWBRAN'},
                     '101184CHRCCHES': {'class': '10',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1984, 10, 11, 0, 0),
                                        'email': 'benthrdunthat@hyperlink.net',
                                        'first': 'Christine',
                                        'group': 'G',
                                        'id': 323,
                                        'last': 'Chesson',
                                        'mailTo': 'Larry and Virginia Chesson',
                                        'sex': 'F',
                                        'swimmer_id': '101184CHRCCHES'},
                     '101885JESSBROW': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1985, 10, 18, 0, 0),
                                        'email': 'BrownFamilt12@earthlink.com',
                                        'first': 'Jessica',
                                        'group': 'G',
                                        'id': 202,
                                        'last': 'Brown',
                                        'mailTo': 'Bill & Mary Brown',
                                        'sex': 'F',
                                        'swimmer_id': '101885JESSBROW'},
                     '101986HEAJGEAR': {'class': '9',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 10, 19, 0, 0),
                                        'email': 'gearys@livenet.com',
                                        'first': 'Heather',
                                        'group': 'G',
                                        'id': 17,
                                        'last': 'Geary',
                                        'mailTo': 'Steven & Dawn Geary',
                                        'sex': 'F',
                                        'swimmer_id': '101986HEAJGEAR'},
                     '101988CANLLAND': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1988, 10, 19, 0, 0),
                                        'email': '',
                                        'first': 'Candice',
                                        'group': 'G',
                                        'id': 161,
                                        'last': 'Landau',
                                        'mailTo': '',
                                        'sex': 'F',
                                        'swimmer_id': '101988CANLLAND'},
                     '102089PATJMALL': {'class': '5',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 10, 20, 0, 0),
                                        'email': 'duckfam@hotmail.com',
                                        'first': 'Patrick',
                                        'group': 'G',
                                        'id': 331,
                                        'last': 'Mallard',
                                        'mailTo': 'Tammy & Joe Mallard',
                                        'sex': 'M',
                                        'swimmer_id': '102089PATJMALL'},
                     '102288MERLBRIN': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1988, 10, 22, 0, 0),
                                        'email': 'BrindleFamily@dcc.net',
                                        'first': 'Meredith',
                                        'group': 'G',
                                        'id': 86,
                                        'last': 'Brindle',
                                        'mailTo': 'Lee and Kathy Brindle',
                                        'sex': 'F',
                                        'swimmer_id': '102288MERLBRIN'},
                     '103089LISMGUND': {'class': '5',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 10, 30, 0, 0),
                                        'email': 'gunders@aol.com',
                                        'first': 'Lisa',
                                        'group': 'G',
                                        'id': 326,
                                        'last': 'Gunderson',
                                        'mailTo': 'Sandra & Ed Gunderson',
                                        'sex': 'F',
                                        'swimmer_id': '103089LISMGUND'},
                     '103089MAREANDR': {'class': '6',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 10, 30, 0, 0),
                                        'email': 'hterror@aol.com',
                                        'first': 'Mary',
                                        'group': 'G',
                                        'id': 315,
                                        'last': 'Andrews',
                                        'mailTo': 'Jared and Jennifer Andrews',
                                        'sex': 'F',
                                        'swimmer_id': '103089MAREANDR'},
                     '111389BRAMMANS': {'class': '5',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 11, 13, 0, 0),
                                        'email': 'bel_lan@vericom.net',
                                        'first': 'Brandy',
                                        'group': 'G',
                                        'id': 50,
                                        'last': 'Mansfield',
                                        'mailTo': 'Lance & Belinda Mansfield',
                                        'sex': 'F',
                                        'swimmer_id': '111389BRAMMANS'},
                     '111789ELINMUNS': {'class': '5',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 11, 17, 0, 0),
                                        'email': 'MUNSON.V-M@JUNO.COM',
                                        'first': 'ELIZABETH',
                                        'group': 'G',
                                        'id': 7,
                                        'last': 'MUNSON',
                                        'mailTo': 'Margaret & Victor Munson',
                                        'sex': 'F',
                                        'swimmer_id': '111789ELINMUNS'},
                     '112982EMILDENV': {'class': '12',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1982, 11, 29, 0, 0),
                                        'email': 'denverhome@webnet.com',
                                        'first': 'Emily',
                                        'group': 'G',
                                        'id': 114,
                                        'last': 'Denver',
                                        'mailTo': 'Caroline & Ben Denver',
                                        'sex': 'F',
                                        'swimmer_id': '112982EMILDENV'},
                     '120286MARLMORT': {'class': '8',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 12, 2, 0, 0),
                                        'email': '',
                                        'first': 'MARTHA',
                                        'group': 'G',
                                        'id': 155,
                                        'last': 'MORTENSEN',
                                        'mailTo': 'Rose Ann & Ken Mortensen',
                                        'sex': 'F',
                                        'swimmer_id': '120286MARLMORT'},
                     '121487ALLEBRAY': {'class': '7',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1987, 12, 14, 0, 0),
                                        'email': 'GBrayson@networld.com',
                                        'first': 'Allison',
                                        'group': 'G',
                                        'id': 49,
                                        'last': 'Brayson',
                                        'mailTo': 'George and Chris Brayson',
                                        'sex': 'F',
                                        'swimmer_id': '121487ALLEBRAY'},
                     '122289TRADWEYM': {'class': '5',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1989, 12, 22, 0, 0),
                                        'email': 'weyup@yahoo.com',
                                        'first': 'Tracy',
                                        'group': 'G',
                                        'id': 324,
                                        'last': 'Weymouth',
                                        'mailTo': 'Wayne & Paula Weymouth',
                                        'sex': 'F',
                                        'swimmer_id': '122289TRADWEYM'},
                     '122486ASHNOLSO': {'class': '10',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1986, 12, 24, 0, 0),
                                        'email': 'fam4swim@crystal.net',
                                        'first': 'Ashley',
                                        'group': 'G',
                                        'id': 275,
                                        'last': 'Olson',
                                        'mailTo': 'Catherine & Charles Olson',
                                        'sex': 'F',
                                        'swimmer_id': '122486ASHNOLSO'},
                     '122691BRIKFREE': {'class': '3',
                                        'club_id': 'CCRR',
                                        'dob': datetime.datetime(1991, 12, 26, 0, 0),
                                        'email': 'freebirds@calnet.com',
                                        'first': 'Brian',
                                        'group': 'G',
                                        'id': 312,
                                        'last': 'Free',
                                        'mailTo': 'Wade & Patricia Free',
                                        'sex': 'M',
                                        'swimmer_id': '122691BRIKFREE'}},
        'title': 'NAC Charity SC Gala 2015'}
